# Generated by Django 4.2.6 on 2023-10-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_team_person_team_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="full_name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(default="none", max_length=100),
            preserve_default=False,
        ),
    ]
